Feature/set models properties
zhihdd/twitter-api-2020 pull request #1
Opened 2021-07-05 17:31 UTC by zhihdd

每個model關聯的設定已設定好，
local 端test也有通過(為通過test，關聯設定與教案有些不同)
model的關聯建立請多幫忙留意。

ZHIH

2021-07-05 17:39 UTC, Jennesy commented on migrations/20190115071420-create-reply.js
> +        type: Sequelize.INTEGER,
是不是不小心加到逗號

2021-07-05 17:42 UTC, Jennesy commented on migrations/20190115071420-create-reply.js
>        comment: {
我們ERD和API document上attribute是命名為content，可以討論一下要命名為"comment"還是"content"。

2021-07-05 17:47 UTC, Jennesy commented on migrations/20190115071420-create-tweet.js
>        description: {
命名跟ERD與API document不一致～

2021-07-05 18:06 UTC, Jennesy commented on models/tweet.js
> +    Tweet.hasMany(models.Like);
可使用
`Tweet.belongsToMany(models.User, {
      through: models.Like,
      foreignKey: "id",
      as: "LikedUsers",
    })`建立tweet與user間的多對多關係，如followship

2021-07-05 18:08 UTC, Jennesy commented on models/user.js
> +    User.hasMany(models.Like);
同理，可使用
User.belongsToMany(models.Tweet, { through: models.Like, foreignKey: "id", as: "LikedTweets", })
來建立多對多關係，如followship

2021-07-06 00:01 UTC, zhihdd commented on migrations/20190115071420-create-reply.js
> +        type: Sequelize.INTEGER,
這我預設格式會幫我處理，我再刪就好

2021-07-06 00:06 UTC, zhihdd commented on migrations/20190115071420-create-reply.js
>        comment: {
OK我照內建的migration 的create-Reply去做調整的 ，但剛看測試檔應該不影響結果，所以我改成"content"好了，這樣文件
也不用動。

2021-07-06 00:06 UTC, zhihdd commented on migrations/20190115071420-create-tweet.js
>        description: {
同上可改~~

2021-07-06 00:09 UTC, zhihdd commented on models/tweet.js
> +    Tweet.hasMany(models.Like);
這邊會這樣用的原因是，測試檔逼我的 QAQ (ry，詳見 test/models/Tweet.pec.js
```
    it('should have many replies', (done) => {
      expect(Tweet.hasMany).to.have.been.calledWith(Reply)
      done()
    })
    it('should have many likes', (done) => {
      expect(Tweet.hasMany).to.have.been.calledWith(Like)
      done()
    })
    it('should belong to user', (done) => {
      expect(Tweet.belongsTo).to.have.been.calledWith(User)
      done()
    })
  })
```
如果不那樣測試不給過

2021-07-06 00:09 UTC, zhihdd commented on models/user.js
> +    User.hasMany(models.Like);
同上(ry QWQ

2021-07-06 01:24 UTC, Jennesy commented on models/tweet.js
> +    Tweet.hasMany(models.Like);
🥲
我想到一個方法，就是兩個都放。
`Tweet.hasMany(models.Like)`
`Tweet.belongsToMany(models.User, { through: models.Like, foreignKey: "id", as: "LikedUsers", }) `
同時都放⬆️

2021-07-06 01:27 UTC, zhihdd commented on models/tweet.js
> +    Tweet.hasMany(models.Like);
不知道會不會衝突，不過可以放放看www，我等等放

2021-07-06 01:40 UTC, Jennesy requested changes
統一整理：
1. 更改Reply與Tweet model ‘content’參數的命名
2. 嘗試加User和Tweet `belongsToMany` Like的association

2021-07-06 01:59 UTC, Jennesy approved these changes
Good!

2021-07-06 01:59 UTC, merged