Feature/add condition role
zhihdd/twitter-api-2020 pull request #35
Opened 2021-07-09 17:00 UTC by zhihdd

增加 where: { role :user}的限制
以及 POST DELETE PUT 等動作若role不符合就不給執行

2021-07-09 18:25 UTC, Jennesy commented on controllers/api/userController.js
> +    if (req.user.role === 'admin') {
這部分`authenticatedUser`在routes會先擋
我覺得可以不用在controller裡再次判斷

2021-07-09 18:26 UTC, Jennesy commented on controllers/api/adminController.js
> +    if(req.user.role !== 'admin'){
這部分`authenticatedAdmin`在routes會先擋
我覺得可以不用在controller裡再次判斷

2021-07-09 18:42 UTC, Jennesy requested changes
`postUser`的**accountCheck**和**emailCheck**也要加`where: {role: 'user'}`
`getUser`的`User.findByPk`也要加`where: {role: 'user'}`

2021-07-09 19:09 UTC, zhihdd commented
> getUser的User.findByPk也要加where: {role: 'user'}
這部分需要保留能夠看得到admin 帳號資訊，還是限制只看user的就好

2021-07-09 19:10 UTC, zhihdd commented on controllers/api/adminController.js
> +    if(req.user.role !== 'admin'){
OK 我會修掉

2021-07-10 01:16 UTC, Jennesy commented
以下這些controller裡的`if(req.user.role !== 'user')...`也都可以拿掉
因為在`routes`有`authenticatedUser`會擋
- followController: `postFollowship` & `deleteFollowship`
- likeController: `postLike` & `deleteLike`
- replyController: `postReply` 
- tweetController: `postTweet` 
- userController: `putUser`

2021-07-10 01:20 UTC, Jennesy commented
> > getUser的User.findByPk也要加where: {role: 'user'}
> 
> 這部分需要保留能夠看得到admin 帳號資訊，還是限制只看user的就好

Admin能看的資訊只有name和account而已 (感覺沒什麼好看的XD)，我覺得只提供user的就好

2021-07-10 03:09 UTC, zhihdd commented
都改好囉

2021-07-10 05:31 UTC, Jennesy commented
1. putUser的` if (req.user.role === 'admin')` 漏了沒拿掉
2. getUserTweets以及getTweets裡的` where: { role: 'user' }`我個人是覺得可以不用，因為admin不可能發推文

2021-07-10 08:21 UTC, Jennesy approved these changes

2021-07-10 08:55 UTC, merged